# Generated by Django 5.2.4 on 2025-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
