# Generated by Django 5.2.4 on 2025-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration_app", "0002_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
    ]
